services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: projects-api-dynamodb
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
    ports:
      - "8000:8000"
