"""Domain and API models."""

import re
from datetime import UTC, datetime
from enum import StrEnum
from typing import Annotated
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator

from projects_api.domain.validation import validate_name


class ProjectType(StrEnum):
    """What the project will host."""

    AGENT = "agent"
    MCP = "mcp"
    WEB = "web"


class ProjectStatus(StrEnum):
    CREATED = "CREATED"
    PROVISIONING = "PROVISIONING"
    READY = "READY"
    FAILED = "FAILED"


class CreateProjectRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    name: Annotated[
        str,
        Field(
            description="Human-chosen project name. 3 to 63 characters; letters, digits, "
            "spaces, hyphens and underscores. Globally unique, case-insensitive.",
            examples=["my-first-agent"],
        ),
    ]
    type: Annotated[ProjectType, Field(description="What the project will host.")]

    @field_validator("name")
    @classmethod
    def _validate_name(cls, value: str) -> str:
        return validate_name(value)


PROJECT_ID_PREFIX = "prj_"
# Ids are generated by Project.new as PROJECT_ID_PREFIX + uuid4().hex; keep these in step.
PROJECT_ID_PATTERN = re.compile(rf"^{PROJECT_ID_PREFIX}[0-9a-f]{{32}}$")


def is_valid_project_id(value: str) -> bool:
    """True if `value` has the shape of an id produced by `Project.new`."""
    return PROJECT_ID_PATTERN.fullmatch(value) is not None


class Project(BaseModel):
    """A project record as stored and as returned to the caller."""

    model_config = ConfigDict(frozen=True, populate_by_name=True)

    project_id: str = Field(alias="projectId")
    name: str
    type: ProjectType
    status: ProjectStatus
    owner_id: str = Field(alias="ownerId")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")

    @classmethod
    def new(cls, *, name: str, type_: ProjectType, owner_id: str) -> "Project":
        now = datetime.now(UTC).replace(microsecond=0)
        return cls(
            project_id=f"{PROJECT_ID_PREFIX}{uuid4().hex}",
            name=name,
            type=type_,
            status=ProjectStatus.CREATED,
            owner_id=owner_id,
            created_at=now,
            updated_at=now,
        )


class ProjectResponse(Project):
    """Public representation. Same shape as Project, serialised with camelCase keys."""


class ProjectListResponse(BaseModel):
    """One page of the caller's projects, newest first."""

    model_config = ConfigDict(populate_by_name=True)

    items: list[ProjectResponse]
    next_token: str | None = Field(
        default=None,
        alias="nextToken",
        description="Opaque cursor for the next page. Pass it back as `nextToken`; null on "
        "the last page.",
    )
